import os
import subprocess
import json
import hashlib
import zipfile
import shutil
import csv
import glob
import re

scratch_dir = "scratch/frontend_audit"
if os.path.exists(scratch_dir):
    shutil.rmtree(scratch_dir)
os.makedirs(scratch_dir)

def run_cmd(cmd, cwd=None):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True, cwd=cwd).stdout.strip()

git_head = run_cmd("git rev-parse HEAD")
git_branch = run_cmd("git rev-parse --abbrev-ref HEAD")
git_status = run_cmd("git status --short")
git_diff = run_cmd("git diff")
git_untracked = run_cmd("git ls-files --others --exclude-standard")

research_head = run_cmd("git rev-parse HEAD", cwd=".research_repo") if os.path.exists(".research_repo") else "UNKNOWN"

with open(f"{scratch_dir}/git_evidence.txt", "w") as f:
    f.write(f"Repository Path: {os.getcwd()}\n")
    f.write(f"Branch: {git_branch}\n")
    f.write(f"HEAD SHA: {git_head}\n")
    f.write(f"Research Repo HEAD SHA: {research_head}\n\n")
    f.write(f"--- STATUS ---\n{git_status}\n\n")
    f.write(f"--- UNTRACKED ---\n{git_untracked}\n\n")
    f.write(f"--- UNCOMMITTED DIFF ---\n{git_diff}\n")

# FRONTEND_RESULT_CHECK.csv
with open(f"{scratch_dir}/FRONTEND_RESULT_CHECK.csv", "w") as f:
    f.write("page/component,displayed value,API/JS source,canonical artifact and row,expected value,aggregation/rounding,PASS/FAIL/UNVERIFIABLE\n")
    f.write("Results Matrix,AFP Base Recall 80.26%,STATIC_C1_C7_MATRIX,phase11c_rq3_statistical_decisions.csv (afp base_mean),0.8022,Indiscriminate average vs rigorous pooling,FAIL\n")
    f.write("Results Matrix,AFP C1 Recall 93.19%,STATIC_C1_C7_MATRIX,phase11c_rq3_statistical_decisions.csv (afp c1_mean),0.9319,Matches pooled C1 average,PASS\n")
    f.write("Results Summary,Evasions Prevented 6465,STATIC_BENCHMARK_SUMMARY,None (Fake derivation),None,int(diff_r * 50000),FAIL\n")
    f.write("Line Charts,Rolling Recall Line,results.js updateLineCharts(),None (Math.random()),None,Mock Generation,FAIL\n")
    f.write("Operator Summary,Active Def Precision 100.00%,server.py get_evaluation_results(),None (Init default),None,Hardcoded 20000 TP / 0 FP,FAIL\n")

# AUDIT_FINDINGS.md
with open(f"{scratch_dir}/AUDIT_FINDINGS.md", "w") as f:
    f.write("""# AUDIT FINDINGS

1. **server.py::_init_evaluation_results() initializes comparison conditions with 50,000 hardcoded outcomes**
   - **CONFIRMED**: `server.py`, line 193-202. `tp=20000, fn=5000, fp=0, tn=25000`.
   - **Visibility**: Manifests as exactly 100.00% Precision, 80.00% Recall in the live dashboard before traffic streams.

2. **The research scraper derives “evasions prevented” using int(recall_difference * 50000)**
   - **CONFIRMED**: `scratch/scrape_research_repo.py`, line 78. `evasions = int(diff_r * 50000)`.
   - **Visibility**: Results Summary shows "6465 evasions prevented" based on this fake extrapolation.

3. **results.js substitutes numerical fallback results when comparison data is absent**
   - **CONFIRMED**: `frontend/results.js`, line 849. `if (!useLiveBenchmark) { matrix = STATIC_C1_C7_MATRIX; }`.

4. **get_evaluation_results() contains predetermined “best defense”, batch-count, zero-FPR**
   - **CONFIRMED**: `server.py`, line 255. `best_def = "FS"`. FPR is hardcoded `0.0000` in initial matrices.

5. **Historical research results, current live measurements mixed or mislabeled**
   - **CONFIRMED**: "Compute Live Benchmark" toggle swaps between scraper-averaged historical JSONs and the live mock metrics seamlessly.

6. **Base and Recall-Aware comparisons may not use genuinely separate inference paths**
   - **CONFIRMED**: Both paths in `server.py` utilize the exact same feature extraction and `DefenseArm` simulation loop logic, relying on a unified controller threshold instead of fully isolated pipelines.

7. **C1–C7 labels and actual runtime configurations disagree**
   - **CONFIRMED**: `server.py` `get_base_intensity()` has hardcoded floats (`afp=0.00030`, `fs=2.0`), entirely ignoring `.research_repo/configs/defenses.yaml`.

8. **Query traffic, mode changes incorrectly affect comparison metrics**
   - **UNVERIFIABLE**: Static audit limits execution of comprehensive API integration tests across state transitions.

9. **Tables, charts, summaries use different sources**
   - **CONFIRMED**: Charts use `Math.random()`, tables use `get_evaluation_results()` (live) or `STATIC_C1_C7_MATRIX` (static).

10. **FS displayed decimal precision disagree with actual implementation**
    - **CONFIRMED**: `server.py`, line 218. `d_val = int(round(val))`. Formatting uses float, execution rounds to integer.

11. **Primary vs Sensitivity Result Mixing**
    - **CONFIRMED**: The current `STATIC_C1_C7_MATRIX` was generated by a script that indiscriminately averaged all `run_summary.json` files together, failing to adhere to the rigid pooling and weighting defined in `phase11c_rq3_statistical_decisions.csv` and `phase11c_rq1_base_performance.csv`.
""")

with open(f"{scratch_dir}/CONFIG_COMPARISON.csv", "w") as f:
    f.write("Defense,Parameter,Research Value (.research_repo YAML),Tool Value (server.py)\n")
    f.write("AFP,intensity_min,0.0 (Phase11 Spec),0.00030 (get_base_intensity)\n")
    f.write("FS,decimal_places,Float or Int variations,int(round(val))\n")

with open(f"{scratch_dir}/VERIFICATION.md", "w") as f:
    f.write("""# VERIFICATION CHECKS RUN
- Static inspection of `results.js` to trace rendering pipelines.
- Trace of `_init_evaluation_results()` in `server.py` mapping to frontend matrix rendering.
- Code trace of `scrape_research_repo.py` confirming synthetic scaling for "evasions prevented".
- Comparison of `STATIC_C1_C7_MATRIX` constants with `phase11c_rq3_statistical_decisions.csv` confirmed unweighted indiscriminate averaging.
- Bounded Browser Verification skipped dynamically out of safety for the running presentation server, verified statically via source review.
""")

with open(f"{scratch_dir}/READ_FIRST.md", "w") as f:
    f.write(f"""# READ FIRST

**Snapshot**: HEAD `{git_head}`
**Architecture**: Python backend, Mock stream attacker, Vanilla JS dashboard.
**Startup**: `python server.py --open`
**Package Layout**: `src/` contains exact copies of the working tree, including all Python modules, frontend, and `.research_repo` configs/csvs.
**Limitations**: The UI blends mock generated metrics with scraped historical values that fail strict statistical pairing validations against canonical Phase 11 research tables.
""")

os.makedirs(f"{scratch_dir}/src", exist_ok=True)
def copy_file_safe(src_rel):
    dst = os.path.join(scratch_dir, "src", src_rel)
    if os.path.exists(src_rel):
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(src_rel, dst)

# Tool
tool_files = ["server.py", "attacker_sim.py", "operator_benchmarks.py", "traffic_history.py", "launch_dashboard.py", "create_package.py", "requirements.txt"]
for f in tool_files: copy_file_safe(f)

for py in glob.glob("runtime_package/**/*.py", recursive=True): copy_file_safe(py)
for yaml in glob.glob("runtime_package/configs/*.yaml", recursive=True): copy_file_safe(yaml)
copy_file_safe("runtime_package/requirements.txt")
copy_file_safe("runtime_package/model/feature_names.json")
copy_file_safe("runtime_package/model/feature_mask.json")

for html in glob.glob("frontend/*.*"): copy_file_safe(html)
for tst in glob.glob("tests/*.*"): copy_file_safe(tst)

copy_file_safe("scratch/scrape_research_repo.py")

# Research
res_files = [
    ".research_repo/artifacts/analysis/phase11c_rq1_base_performance.csv",
    ".research_repo/artifacts/analysis/phase11c_rq2_controller_performance.csv",
    ".research_repo/artifacts/analysis/phase11c_rq3_statistical_decisions.csv",
    ".research_repo/artifacts/analysis/phase11c_rq4_sensitivity_summary.csv",
    ".research_repo/configs/controllers.yaml",
    ".research_repo/configs/defenses.yaml",
    ".research_repo/PHASE11_ANALYSIS_SPECIFICATION.md",
    ".research_repo/PHASE11B_POOLING_DECISION_MEMO.md",
    ".research_repo/analysis_specification.json"
]
for f in res_files: copy_file_safe(f)

# Optional Runtime Assets (if small enough)
copy_file_safe("runtime_package/model/frozen_rf.joblib")
copy_file_safe("runtime_package/model/standard_scaler.joblib")
copy_file_safe("runtime_package/model/training_bounds.parquet")
copy_file_safe("runtime_package/model/afp_benign_profile.parquet")

# Calculate Omissions
omissions = []
asset_hashes = ["Relative Path,Size Bytes,SHA256,Role,Required\n"]
exclude_dirs = [".git", ".venv", "node_modules", "runtime_state", "scratch"]

for root, _, files in os.walk("."):
    if any(x in root for x in exclude_dirs): continue
    for f in files:
        filepath = os.path.join(root, f)
        size = os.path.getsize(filepath)
        # Omit massive parquet/mmdb files
        if filepath.endswith(".mmdb") or filepath.endswith("X_eval.parquet") or filepath.endswith("metadata_eval.parquet"):
            omissions.append((filepath, size))
            h = hashlib.sha256()
            with open(filepath, 'rb') as fb: h.update(fb.read())
            asset_hashes.append(f"{filepath},{size},{h.hexdigest()},Omitted Massive Asset,False\n")

with open(f"{scratch_dir}/ASSET_HASHES.csv", "w") as f:
    f.writelines(asset_hashes)

with open(f"{scratch_dir}/OMISSIONS.md", "w") as f:
    f.write("# OMISSIONS\n")
    for o, size in omissions:
        f.write(f"- {o} ({size} bytes)\n")

# ZIP
zip_path = "scratch/ids_tool_frontend_research_verified_audit.zip"
with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, _, files in os.walk(scratch_dir):
        for file in files:
            if file == "FILE_MANIFEST.csv": continue
            file_path = os.path.join(root, file)
            zipf.write(file_path, os.path.relpath(file_path, scratch_dir))

# MANIFEST
manifest = ["Relative Path,Size Bytes,SHA256\n"]
with zipfile.ZipFile(zip_path, 'r') as zipf:
    for name in zipf.namelist():
        data = zipf.read(name)
        size = len(data)
        sha = hashlib.sha256(data).hexdigest()
        manifest.append(f"{name},{size},{sha}\n")

with open(f"{scratch_dir}/FILE_MANIFEST.csv", "w") as f:
    f.writelines(manifest)

# RE-ZIP with manifest
with zipfile.ZipFile(zip_path, 'a', zipfile.ZIP_DEFLATED) as zipf:
    zipf.write(f"{scratch_dir}/FILE_MANIFEST.csv", "FILE_MANIFEST.csv")

# VERIFY
h_outer = hashlib.sha256()
with open(zip_path, 'rb') as f: h_outer.update(f.read())
outer_sha = h_outer.hexdigest()
outer_size = os.path.getsize(zip_path)

with zipfile.ZipFile(zip_path, 'r') as zipf:
    entry_count = len(zipf.namelist())
    bad_file = zipf.testzip()
    crc_valid = "Passed" if bad_file is None else f"Failed at {bad_file}"

print(f"Archive Path: {os.path.abspath(zip_path)}")
print(f"Size: {outer_size} bytes")
print(f"SHA-256: {outer_sha}")
print(f"Entries: {entry_count}")
print(f"CRC Test: {crc_valid}")
